export const communesByWilaya: Record<string, string[]> = {
  "01": [
    "Adrar", "Tamentit", "Fenoughil", "Zaouiet Kounta", "In Zghmir", "Tsabit", "Akabli", "Aoulef",
    "Timekten", "Ouled Ahmed Timmi", "Sebaa", "Sali", "Bouda", "Timimoun", "Aougrout", "Charouine",
    "Talmine", "Tinerkouk", "Deldoul", "Ouled Said", "Metarfa", "Reggane", "Ksar Kaddour",
    "Bordj Badji Mokhtar", "Timiaouine", "Tit", "Ouled Aissa", "Tamest",
  ],
  "02": [
    "Chlef", "Tenes", "Benairia", "Beni Haoua", "Sobha", "Tadjena", "Taougrit", "Talassa",
    "Abou El Hassan", "Ouled Fares", "Boukadir", "Beni Rached", "Oued Goussine", "Chettia",
    "Herenfa", "Ouled Abbes", "Dahra", "Oued Sly", "Oued Fodda", "Sendjas", "Zeboudja", "Harchoun",
    "Ouled Ben Abdelkader", "Sidi Abderrahmane", "El Hadjadj", "Moussadek", "Labiod Medjadja",
    "El Marsa", "Breira", "Ain Merane", "Sidi Akkacha", "Bouzeghaia", "El Karimia", "Beni Bouateb",
  ],
  "03": [
    "Laghouat", "Ksar El Hirane", "Hassi Delaa", "Hassi R'Mel", "Sidi Makhlouf", "Ain Madhi",
    "Tadjmout", "Kheneg", "Gueltat Sidi Saad", "El Ghicha", "Brida", "El Houaita", "Sebgag",
    "Aflou", "Tadjrouna", "El Assafia", "Beidha El Hamra", "Oued Morra", "Oued M'Zi",
    "Hadj Mechri", "Taouiala", "Sidi Bouzid", "Mekhareg", "Bouanab",
  ],
  "04": [
    "Oum El Bouaghi", "Ain Beida", "Ain M'lila", "Sigus", "Ain Babouche", "El Belala",
    "Ouled Hamla", "Behir Chergui", "Souk Naamane", "Fkirina", "Zorg", "El Amiria", "Berriche",
    "Bir Chouhada", "El Harmilia", "Ouled Gacem", "Rahia", "Ksar Sbahi", "Dhalaa",
    "Hanchir Toumghani", "Oued Nini", "El Djazia", "Ain Diss", "Ain Kercha", "Ain Fakroun",
    "Meskiana",
  ],
  "05": [
    "Batna", "Arris", "Ain Touta", "Merouana", "Seriana", "Tazoult", "N'Gaous", "Barika",
    "Ras El Aioun", "Bitam", "Chemora", "El Madher", "Menaa", "Inoughissen", "T'Kout",
    "Ouled Sellem", "Ouyoun El Assafir", "El Hassi", "Djerma", "Sefiane", "Foum Toub",
    "Ain Yagout", "Ain Djasser", "Boumagueur", "Maafa", "Lemsane", "Guigba", "Tighanimine",
    "Larbaa", "Seggana", "Bouzina", "Ouled Aouf", "Taxlent", "Gosbat", "Talkhamt",
    "Hidoussa", "Zanat El Beida", "Oued Chaaba", "Boulhilet", "Fesdis", "Ksar Bellezma",
    "Chir", "Ouled Fadel", "Djezar", "Ain Tagrout", "Tilatou", "Rahbat", "Timgad",
  ],
  "06": [
    "Bejaia", "Amizour", "Aokas", "Tichy", "Akbou", "Sidi Aich", "El Kseur", "Souk El Tenine",
    "Adekar", "Tazmalt", "Seddouk", "Ighram", "Beni Maouche", "Chemini", "Akfadou", "Kherrata",
    "Darguina", "Timezrit", "Souk Oufella", "Toudja", "Sidi Ayad", "Tinebdar", "Boukhelifa",
    "Barbacha", "El Flaye", "Taourirt Ighil", "Ighil Ali", "Beni Ksila", "Tibane", "Adekar",
    "Melbou", "Kendira", "M'Cisna", "Tamridjet", "Ouzellaguen", "Draa El Kaid",
    "Leflaye", "Boudjellil", "Fenaia Il Maten", "Taskriout", "Smaoun", "Beni Djellil",
    "Amalou", "Tifra", "Sidi Aich", "Souk El Tenine",
  ],
  "07": [
    "Biskra", "El Outaya", "Sidi Okba", "Tolga", "Ouled Djellal", "Foughala", "Lioua",
    "M'Ziraa", "El Feidh", "El Ghrous", "Branis", "Zeribet El Oued", "Ain Naga", "Djemorah",
    "Chetma", "El Kantara", "El Hadjeb", "Bouchagroun", "Sidi Khaled", "Ras El Miaad",
    "Doucen", "Mekhadma", "Bordj Ben Azzouz", "El Mizraa",
  ],
  "08": [
    "Bechar", "Kenadsa", "Abadla", "Beni Ounif", "Lahmar", "Mogheul", "Erg Ferradj",
    "Taghit", "Meridja", "Tabelbala", "Beni Abbes", "Igli", "Kerzaz", "Ouled Khoudir",
    "Timoudi", "Beni Ikhlef",
  ],
  "09": [
    "Blida", "Boufarik", "Larbaa", "Bouinan", "Ouled Yaich", "Souhane", "Beni Mered",
    "Bougara", "El Affroun", "Mouzaia", "Chebli", "Chrea", "Ben Khelil", "Meftah",
    "Soumaa", "Oued Alleug", "Beni Tamou", "Ain Romana", "Guerrouaou", "Bouarfa",
    "Hammam Melouane", "Chiffa", "Djebabra", "El Bouaiche", "Naciria",
  ],
  "10": [
    "Bouira", "Sour El Ghozlane", "Ain Bessem", "Lakhdaria", "Bechloul", "El Adjiba",
    "Kadiria", "Ahl El Ksar", "M'Chedallah", "Bordj Okhriss", "Hadjera Zerga", "Sour",
    "Dirah", "El Hachimia", "Ain El Turk", "El Khebouzia", "Ain Laloui", "Aomar",
    "Maamora", "Souk El Khemis", "Ridane", "Aghbalou", "Saharidj", "Raouraoua",
    "Bir Ghbalou", "Taghzout", "Hanif", "Guerrouma", "Chorfa", "Hadjout (Bouira)",
    "Djebahia", "Bouderbala", "El Hakimia", "Mezdour", "Ain El Hadjar", "Ath Mansour",
    "Oued El Berdi", "Bordj Bouhdjar", "El Asnam", "Boukram", "Zbarbar", "Haizer",
    "Taguedite", "Magramane", "Souk El Khemis",
  ],
  "11": [
    "Tamanrasset", "Abalessa", "In Ghar", "In Salah", "In Amguel", "Tazrouk", "Idles",
    "Tin Zaouatine", "Foggaret Ezzaouia",
  ],
  "12": [
    "Tebessa", "Bir El Ater", "Cheria", "El Aouinet", "El Kouif", "Stah Guentis",
    "El Ogla", "El Houidjbet", "Ferkane", "Ain Zerga", "Boukhadra", "Bekkaria",
    "Hammamet", "Negrine", "Saf Saf El Ouesra", "El Ogla El Malha", "El Mezeraa",
    "Bedjene", "Morsott", "Oum Ali", "El Mridj", "Gorriguer", "Boulhaf Dyr",
    "Telidjene", "Bir Mokkadem", "Souk Ahras boundary", "Ain Zerga", "El Aouinet",
  ],
  "13": [
    "Tlemcen", "Mansourah", "Chetouane", "Remchi", "Beni Mester", "Sebbaa Chioukh",
    "El Fehoul", "Bab El Assa", "Sidi Medjahed", "Ghazaouet", "Souani", "Honaine",
    "Souahlia", "Tianet", "Sidi Abdelli", "Hennaya", "Ouled Mimoun", "Ain Youcef",
    "Ain Fezza", "Ain Nehala", "Beni Snous", "Bensekrane", "El Gor", "Ain Ghoraba",
    "Beni Boussaid", "Sebdou", "Sidi Djillali", "El Aricha", "Azails", "Bouihi",
    "Msirda Fouaga", "Dar Yaghmouracene", "Nedroma", "Marsa Ben M'Hidi", "Souk Tlata",
    "Fellaoucene", "Zenata", "Amieur", "Beni Add", "Terny Beni Hediel", "Sidi Ben Adda",
    "Oued Lakhdar", "El Bouihi", "Ain Tallout", "Djebala", "Beni Bahdel",
    "Bouhlou", "Maghnia", "Hammam Boughrara", "El Gor", "Sabra",
  ],
  "14": [
    "Tiaret", "Mahdia", "Sougueur", "Frenda", "Ksar Chellala", "Ain Deheb", "Medroussa",
    "Mellakou", "Naima", "Sidi Hosni", "Rahouia", "Sebt", "Tousnina", "Zmalet El Emir Abdelkader",
    "Ain Bouchekif", "Oued Lilli", "Si Abdelghani", "Meghila", "Ain Kermes", "Faidja",
    "Tagdempt", "Madna", "Guertoufa", "Sidi Abderrahmane", "Sidi Ali Mellal", "Dahmouni",
    "Mechraa Safa", "Zaarouria", "Hamadia", "Djebilet Rosfa", "Nadorah", "Takhemaret",
    "Bougara", "Tidda", "Ain El Hadid", "Sidi Bakhti", "Chehaima", "Rechaiga",
    "Serghine", "Medrissa", "Mellakou",
  ],
  "15": [
    "Tizi Ouzou", "Ain El Hammam", "Azazga", "Larbaa Nath Irathen", "Boghni", "Draa El Mizan",
    "Tigzirt", "Azeffoun", "Ouaguenoun", "Mekla", "Ouadhias", "Maatkas", "Beni Douala",
    "Iferhounene", "Bouzeguene", "Illoula Oumalou", "Akbil", "Yakouren", "Souama",
    "Tirmitine", "Frikat", "Ait Yahia", "Ait Chafaa", "Mechtras", "Boudjima", "Ait Aggouacha",
    "Tadmait", "Timizart", "Freha", "Sidi Naamane", "Souk El Tenine", "Akerrou",
    "Tizi Rached", "Tizi Gheniff", "Ait Boumahdi", "Ifigha", "Idjeur", "Mizrana",
    "Abi Youcef", "Beni Zmenzer", "Ait Yahia Moussa", "Iboudraren", "Imsouhal",
    "Zekri", "Bounouh", "M'kira", "Ait Toudert", "Yatafen", "Tizi N'Tleta",
    "Beni Aissi", "Aghribs", "Pacha", "Makouda", "Assi Youcef", "Irdjen",
    "Ain Zaouia", "Tizi N'Thlata", "Beni Yenni", "Illilten", "Ait Mahmoud",
    "Djebahia", "Tirmitine", "Sidi Naamane", "M'Kira",
  ],
  "16": [
    "Alger Centre", "Sidi M'Hamed", "El Madania", "Hamma Anassers", "Bab El Oued",
    "Bologhine", "Casbah", "Oued Koriche", "Bir Mourad Rais", "El Biar", "Bouzareah",
    "Birkhadem", "El Harrach", "Baraki", "Oued Smar", "Bachdjerah", "Hussein Dey",
    "Kouba", "Bourouba", "Mohammadia", "Bordj El Kiffan", "El Magharia", "Dar El Beida",
    "Bab Ezzouar", "Ben Aknoun", "Dely Ibrahim", "El Hammamet", "Rais Hamidou",
    "Djasr Kasentina", "El Mouradia", "Hydra", "Mouzaia (Alger)", "Sidi Bel Abbes (Alger)",
    "Bains Romains", "Reghaia", "Ain Taya", "Bordj El Bahri", "Marsa", "H'Raoua",
    "Rouiba", "Heuraoua", "Sidi M'Hamed", "Zeralda", "Mahelma", "Rahmania", "Souidania",
    "Cheraga", "Ouled Fayet", "El Achour", "Draria", "Douera", "Baba Hassen",
    "Khraicia", "Saoula", "Birtouta", "Tessala El Merdja", "Sidi Abdellah",
    "Mahelma", "Staoueli", "Ain Benian", "Bordj El Kiffan",
  ],
  "17": [
    "Djelfa", "Moudjebara", "Ain Oussera", "Hassi Bahbah", "Birine", "Charef", "Messaad",
    "Sed Rahal", "Tadmit", "Hassi El Euch", "Faidh El Botma", "Sidi Baizid", "Guettara",
    "Ain Chouhada", "El Idrissia", "Dar Chioukh", "Zaccar", "Selmana", "Beni Yagoub",
    "Hadj Khelifa", "Bouira Lahdab", "Amourah", "Deldoul", "Ain El Ibel", "Mliliha",
    "Zaafrane", "El Guedid", "Sidi Ladjel", "Had Sahary", "Bouathlani", "Demed",
    "Benhar", "Ain Maabed", "M'Liliha", "Douis", "Birine",
  ],
  "18": [
    "Jijel", "El Milia", "Taher", "Texenna", "Chekfa", "Sidi Marouf", "Settara",
    "El Ancer", "Erraguene", "Ziama Mansouriah", "Kaous", "Boudria Beni Yadjis",
    "El Aouana", "Djimla", "Bouraoui Belhadef", "Sidi Abdelaziz", "Selma Benziada",
    "Emir Abdelkader", "Ouled Yahia Khadrouch", "Ouadjana", "Khiri Oued Adjoul",
    "Bouchtata", "Erraguene El Mahdi", "Boussif Ouled Askeur", "Sidi Marouf",
    "El Kennar Nouchfi", "Ghebala", "Ouled Rabah",
  ],
  "19": [
    "Setif", "El Eulma", "Ain Oulmene", "Bougaa", "Ain Abessa", "Ait Tizi", "Beidha Bordj",
    "Bir El Arch", "Tachouda", "Salah Bey", "Bouandas", "Hammam Soukhna", "Ain Azel",
    "Guellal", "Beni Aziz", "Bazer Sakra", "Babor", "Maaouia", "Guidjel", "Rosfa",
    "Beni Ouartilane", "Mezloug", "Ait Naoual Mezada", "El Ouldja", "Boutaleb",
    "Tizi N'Bechar", "Hammam Guergour", "Draa Kebila", "Beni Chebana", "Belaa",
    "Serdj El Ghoul", "Ksar El Abtal", "Ain Lahdjar", "Bir Haddada", "Harbil",
    "Djemila", "Ain Roua", "Tella", "Amoucha", "Ouled Si Ahmed", "Ain Sebt",
    "Ouled Tebben", "Ain Legradj", "Talaifacene", "Hamma", "El Ouricia",
    "Beni Hocine", "Dehamcha", "Guenzet", "El Eulma", "Setif", "Ouled Addouane",
    "Bir Bouhouche", "Ksar Sbihi", "Ouled Sabor", "Ain Abassa", "Bouhira",
  ],
  "20": [
    "Saida", "Ain El Hadjar", "Sidi Boubekeur", "El Hassasna", "Youb", "Hounet",
    "Doui Thabet", "Ouled Khaled", "Ain Sekhouna", "Moulay Larbi", "Maamora",
    "Tircine", "Sidi Ahmed", "Sidi Amar", "Ouled Brahim", "Sidi Boubekeur",
  ],
  "21": [
    "Skikda", "Collo", "El Hadaiek", "Azzaba", "Ain Kechra", "Ramdane Djamel",
    "Ben Azzouz", "El Harrouch", "Ouled Habba", "Tamalous", "Beni Oulbane", "Bouchtata",
    "Sidi Mezghiche", "Cheraia", "Zitouna", "Filfila", "Ben Bechir", "Salah Bouchaour",
    "Ouled Attia", "Bekkouche Lakhdar", "El Marsa", "Kanoua", "Beni Bechir",
    "Es Sebt", "Oum Toub", "Hammadi Krouma", "Sidi Hecine", "Ain Bouziane",
    "El Ghedir", "Bin El Ouiden", "Ain Charchar", "Zerdezas", "Khenag Mouhag",
    "Ouldja Boulbalout", "Brahim Bouatous", "Beni Zid", "El Arrouch", "Oued Zhour",
  ],
  "22": [
    "Sidi Bel Abbes", "Telagh", "Sfisef", "Ras El Ma", "Ain El Berd", "Mostefa Ben Brahim",
    "Tessala", "Mezaourou", "Hassi Zahana", "Sidi Lahcene", "Sidi Brahim", "Sidi Yacoub",
    "Tabia", "Tafissour", "Boukhanafis", "Marhoum", "Ain Thrid", "Sidi Khaled",
    "Sidi Chaib", "Sidi Ali Boussidi", "Sehala Thaoura", "Ben Badis", "Lamtar",
    "Moulay Slissen", "Belarbi", "Tenira", "Mezaourou", "Oued Sefioun", "Sidi Hamadouche",
    "Mcid", "Chetouane Belaila", "El Hacaiba", "Redjem Demouche", "Zerouala",
    "Ain Adden", "Tilmouni", "Mostefa Ben Brahim", "Makedra", "Sidi Dahou Dzairs",
    "Ain Tindamine", "Oued Taourira", "M'Hajeba", "El Bnoud",
  ],
  "23": [
    "Annaba", "El Bouni", "El Hadjar", "Sidi Amar", "Berrahal", "Chetaibi", "Seraidi",
    "Eulma (Annaba)", "Treat", "El Eulma (Annaba)", "Oued El Aneb",
  ],
  "24": [
    "Guelma", "Bouchegouf", "Oued Zenati", "Heliopolis", "Ain Makhlouf", "Khezara",
    "Hammam Debagh", "Bouhachana", "Belkheir", "Houari Boumediene", "Ain Reggada",
    "Medjez Amar", "Roknia", "Nechmaya", "Ain Sandel", "Ain Larbi", "Bouati Mahmoud",
    "Tamlouka", "Dahouara", "El Fedjoudj Boughrara Saoudi", "Hammam N'Bail",
    "Ain Hessainia", "Djeballah Khemissi", "Ain Ben Beida", "Bordj Sabath",
    "Guelaat Bou Sbaa", "Ras El Agba", "Oued Cheham",
  ],
  "25": [
    "Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad", "Zighoud Youcef",
    "Ain Smara", "Ibn Ziad", "Ouled Rahmoune", "Ain Abid", "Beni Hamiden", "Messaoud Boudjeriou",
  ],
  "26": [
    "Medea", "Ksar El Boukhari", "Berrouaghia", "Ouzera", "Ain Boucif", "Tablat",
    "Ouled Antar", "Beni Slimane", "Si Mahdjoub", "El Omaria", "Sidi Naamane",
    "Boughezoul", "Aziz", "Ouled Bouachra", "Ouled Brahim", "Hannacha", "Ouled Maaref",
    "Sidi Zahar", "Tafraout", "Meghraoua", "Bouchrahil", "Tamesguida", "El Azizia",
    "Aissaouia", "Khams Djouamaa", "Saneg", "Sedraya", "El Hamdania", "Beni Slimane",
    "Ouled Deide", "Derrag", "Mihoub", "Maghraoua", "Ouled Hellal", "Souagui",
    "Boughara", "Bir Ben Laabed", "Rebaia", "Seghouane", "Chahbounia", "Ouamri",
    "Zoubiria", "Tlatet Eddoair", "El Guelb El Kebir", "Ouled Antar", "Bouaiche",
    "Draa Essamar", "El Hamdania", "Kef Lakhdar", "Ouled Brahim", "Bouaiche",
    "Souaghi", "Aissaouia", "El Guelb El Kebir", "Tizi Mahdi", "Beni Slimane",
    "Sidi Errabia", "Mezerana", "Boughzoul", "Cheneguel",
  ],
  "27": [
    "Mostaganem", "Ain Tedles", "Sour", "Bouguirat", "Sayada", "Mesra", "Hassi Mameche",
    "Khadra", "Fornaka", "Sidi Ali", "Ain Nouissy", "Achaacha", "Hassiane",
    "Tazgait", "Ouled Maallah", "Mansourah", "Stidia", "Souaflia", "Sidi Lakhdar",
    "Abdelmalek Ramdane", "Sidi Bel Attar", "Khairat", "Safsaf", "Sidi Belattar",
    "Touahria", "Nekmaria", "Mazagran", "El Hassiane", "Hadjadj", "Ouled Boughalem",
    "Sirat", "Ain Boudinar",
  ],
  "28": [
    "M'Sila", "Bou Saada", "Ain El Melh", "Sidi Aissa", "Magra", "Tarmount", "Khoubana",
    "Berhoum", "Ouled Slama", "Beni Ilmane", "Ouled Madhi", "Ain El Hadjel", "Maadid",
    "Hammam Dalaa", "Sidi Hadjeres", "Mtarfa", "Belaiba", "Ouled Derradj", "Souamaa",
    "Tamsa", "Khettouti Sed El Djir", "Dehahna", "Ben Srour", "Slim", "Ouanougha",
    "M'Cif", "Bouti Sayah", "Sidi Ameur", "Chellal", "El Houamed", "Medjedel",
    "El Hamel", "Zarzour", "Bir Foda", "Djebel Messaad", "Ain Khadra", "Ouled Sidi Brahim",
    "El Mesrane", "Sidi M'Hamed", "Ksar El Boukhari (M'Sila)", "Maarif", "Berhoum",
    "Hadj Mechri", "El Hamel", "Slim", "Tadmit", "Ben Zouh",
  ],
  "29": [
    "Mascara", "Tighennif", "Sig", "Mohammadia", "Ghriss", "Bouhanifia", "Froha",
    "Hacine", "Zahana", "Oued Taria", "Khalouia", "El Bordj", "El Gaada", "Ain Fares",
    "El Menaouer", "Matemore", "El Hachem", "Sidi Boussaid", "Maoussa", "Ain Ferah",
    "Tizi", "Sidi Kada", "Aouf", "Nesmoth", "Makdha", "El Keurt", "El Ghomri",
    "Alaimia", "Sidi Abdeldjebar", "Guettena", "Ain Ferah", "Chorfa", "Zelmata",
    "Benian", "El Gueitena", "Sehailia", "Sidi Boussaid", "Mamounia", "El Hachem",
    "Maoussa", "Oggaz", "Bou Hanifia",
  ],
  "30": [
    "Ouargla", "Hassi Messaoud", "Rouissat", "N'Goussa", "Ain Beida", "Sidi Khouiled",
    "Hassi Ben Abdellah", "El Hadjira", "Ngoussa",
  ],
  "31": [
    "Oran", "Es Senia", "Bir El Djir", "Arzew", "Bethioua", "Marsat El Hadjadj",
    "Ain El Turck", "Mers El Kebir", "Oued Tlelat", "Tafraoui", "Sidi Chami",
    "El Kerma", "Hassi Ben Okba", "Boutlelis", "Ain El Bia", "El Ançor", "Bousfer",
    "Gdyel", "Hassi Mefsoukh", "Ben Freha", "Hassi Bounif", "El Braya", "El Karma",
    "Sidi Ben Yebka", "Misserghin", "Mesra (Oran)",
  ],
  "32": [
    "El Bayadh", "Boualem", "Brezina", "Bougtoub", "El Abiodh Sidi Cheikh", "El Kheiter",
    "Stitten", "Cheguig", "Rogassa", "Tousmouline", "El Mehara", "Kef El Ahmar",
    "Ghassoul", "Arbaouet", "Boussemghoun", "Sidi Slimane", "Sidi Tifour",
    "Krakda", "El Bnoud (El Bayadh)",
  ],
  "33": [
    "Illizi", "Djanet", "Bordj El Haouas", "In Amenas", "Bordj Omar Driss", "Debdeb",
  ],
  "34": [
    "Bordj Bou Arreridj", "Ras El Oued", "Mansoura", "Bordj Zemoura", "El Achir",
    "Medjana", "Ain Taghrout", "Tafreg", "Colla", "Teniet En Nasr", "El Mhir",
    "Ouled Brahem", "Bordj Ghdir", "Belimour", "Ksour", "El Hamadia", "El Anseur",
    "Hasnaoua", "Djaafra", "Sidi Embarek", "Khelil", "Tixter", "Bir Kasdali",
    "Ain Tesra", "El Main", "Rabta", "El Mhir", "Ouled Sidi Brahim", "Belimour",
    "Bordj Ghdir", "Hasnaoua", "Ras El Oued", "Tesmart",
  ],
  "35": [
    "Boumerdes", "Bordj Menaiel", "Naciria", "Khemis El Khechna", "Larbatache",
    "Thenia", "Issers", "Isser", "Chabet El Ameur", "Si Mustapha", "Beni Amrane",
    "Boudouaou", "Boudouaou El Bahri", "Hammedi", "Ouled Moussa", "Ammal",
    "Souk El Had", "Sidi Daoud", "Tidjelabine", "Dellys", "Ben Choud", "Afir",
    "Timezrit", "Baghlia", "Taourga", "Zemmouri", "Khemis El Khechna", "El Kharrouba",
    "Ouled Aich", "Djinet", "Beni Amrane",
  ],
  "36": [
    "El Tarf", "Ben M'Hidi", "Bouhadjar", "Dréan", "Besbes", "El Aioun", "Chebaita Mokhtar",
    "Ain El Assel", "Chihani", "Berihane", "Zitouna", "Lac Des Oiseaux", "Hammam Beni Salah",
    "El Ayoun", "Bouteldja", "Echatt", "Asfour", "Souarekh", "Raml Souk", "Zerizer",
    "Oued Zitoun",
  ],
  "37": [
    "Tindouf", "Oum El Assel",
  ],
  "38": [
    "Tissemsilt", "Theniet El Had", "Bordj Bounaama", "Khemisti", "Lazharia", "Ammari",
    "Sidi Lantri", "Sidi Boutouchent", "Layoune", "Beni Chaib", "Larbaa", "Tamellaht",
    "Melaab", "Boucaid", "Maacem", "Ouled Bessem", "Sidi Slimane", "Youssoufia",
    "Bordj El Emir Abdelkader", "Tamalaht", "Lardjem", "Sidi Abed",
  ],
  "39": [
    "El Oued", "Robbah", "Guemar", "Kouinine", "Reguiba", "Magrane", "Nakhla",
    "Hassani Abdelkrim", "Hamraia", "Bayadha", "Taghzout", "Trifaoui", "Mih Ouansa",
    "Sidi Aoun", "Debila", "Hassi Khalifa", "Beni Guecha",
  ],
  "40": [
    "Khenchela", "Kais", "El Hamma", "Baghai", "Ain Touila", "Bouhmama", "Chechar",
    "Mtoussa", "Babar", "El Oueldja", "Khirane", "Tamza", "Yabous", "Djellal",
    "Cherchar", "Msara", "Remila", "Ouled Rechache", "Taouzianat", "El Mahmal",
    "Ensigha",
  ],
  "41": [
    "Souk Ahras", "Sedrata", "Mechroha", "M'Daourouch", "Taoura", "Ouled Driss",
    "Khedara", "Bir Bouhouche", "Drea", "Hanancha", "Ain Zana", "Sidi Fredj",
    "Zaarouria", "Tiffech", "Oum El Adhaim", "Ouled Moumen", "Haddada", "Ain Soltane",
    "Ain Makhlouf", "Safel El Ouiden", "Heddada", "Merahna", "Zouabi", "Bir Bouhouche",
    "Ragouba Sidi Saad", "Sidi Fredj",
  ],
  "42": [
    "Tipaza", "Cherchell", "Hadjout", "Kolea", "Fouka", "Bou Ismail", "Damous",
    "Sidi Amar", "Gouraya", "Sidi Rached", "Menaceur", "Ain Tagourait", "Nador",
    "Bourkika", "Sidi Ghiles", "Larhat", "Hadjret Ennous", "Ahmer El Ain",
    "Khemisti", "Beni Milleuk", "Messelmoun", "Douaouda", "Chaiba", "Attatba",
    "Sidi Semiane", "Mered", "Aghbal",
  ],
  "43": [
    "Mila", "Chelghoum Laid", "Ferdjioua", "Tadjenanet", "Oued Athmenia", "Grarem Gouga",
    "Telerghma", "Oued Endja", "Ahmed Rachedi", "Ain Mlouk", "Sidi Merouane",
    "Terrai Bainen", "Tassadane Haddada", "Tiberguent", "Hamala", "Zghaia",
    "Yahia Beni Guecha", "Amira Arras", "El Mechira", "Minar Zarza", "Benyahia Abderrahmane",
    "Rouached", "El Rouached", "Ain Tine", "Tassala Lemtai", "Bouhatem", "Derradji Bousselah",
    "Oued Seguen", "El Milia (Mila)", "Sidi Khelifa", "Oued Athmenia", "Chigara",
  ],
  "44": [
    "Ain Defla", "Khemis Miliana", "Miliana", "El Attaf", "Djendel", "Hammam Righa",
    "El Abadia", "Rouina", "Bourached", "Boumedfaa", "Ain Lechiakh", "Ain Torki",
    "Ben Allal", "Hoceinia", "Tarik Ibn Ziad", "El Amra", "Djelida", "Bathia",
    "Tachta Zegagha", "Zeddine", "El Hassania", "Bir Ould Khelifa", "Ain Bouyahia",
    "Sidi Lakhdar", "El Maine", "Oued Chorfa", "Hadjadj", "Belaas", "Mekhatria",
    "El Amra", "Tiberkanine", "Djemaa Ouled Cheikh", "Arib", "El Hassania",
    "Ain Soltane",
  ],
  "45": [
    "Naama", "Mecheria", "Ain Sefra", "Tiout", "Sfissifa", "Moghrar", "Asla",
    "Makman Ben Amer", "El Biod", "Djeniane Bourzeg",
  ],
  "46": [
    "Ain Temouchent", "Hammam Bouhadjar", "El Malah", "Beni Saf", "Aghlal", "Ain El Arbaa",
    "El Amria", "Chaabat El Ham", "Ouled Boudjemaa", "Hassi El Ghella", "Tamzoura",
    "Sidi Ben Adda", "Ain Kihal", "Terga", "El Emir Abdelkader", "Sidi Boumediene",
    "Oued Berkeche", "El Messaid", "Oued Sabah", "Ouled Kihal", "Chentouf",
    "El Maleh", "Hassasna", "Sidi Ouriache", "Tadmaya", "El Amria",
    "Aoubellil", "El Malah",
  ],
  "47": [
    "Ghardaia", "Metlili", "El Atteuf", "Berriane", "Guerrara", "Zelfana", "El Guerrara",
    "Dhayet Bendhahoua", "Bounoura", "El Meniaa", "Hassi Gara", "Hassi Fehal",
    "Sebseb",
  ],
  "48": [
    "Relizane", "Oued Rhiou", "Mazouna", "Yellel", "Zemmoura", "Ammi Moussa",
    "Mediouna", "El Matmar", "Sidi Saada", "Ouarizane", "El Hamadna", "Sidi M'Hamed Ben Ali",
    "Sidi Khettab", "Belaassel Bouzegza", "Beni Dergoun", "Ramka", "Djidiouia",
    "El Guettar", "Mendes", "Souk El Haad", "Ain Tarek", "Ain Rahma", "Oued Essalem",
    "Hamri", "El Hassi", "Lahlef", "Kouider Bou Medienne", "Sidi Lazreg", "Beni Zentis",
    "Mediouna", "Yelel", "El Hassi", "Sidi M'Hamed Ben Ali",
  ],
  "49": [
    "Timimoun", "Aougrout", "Charouine", "Deldoul", "Metarfa", "Ouled Said", "Talmine",
    "Tinerkouk", "Tsabit", "Ouled Aissa", "Tamentit",
  ],
  "50": [
    "Bordj Badji Mokhtar", "Timiaouine",
  ],
  "51": [
    "Ouled Djellal", "Ras El Miaad", "Sidi Khaled", "Doucen", "Besbes", "El Yamen",
  ],
  "52": [
    "Beni Abbes", "Beni Ikhlef", "Igli", "Kerzaz", "Ouled Khoudir", "Tabelbala", "Timoudi",
  ],
  "53": [
    "In Salah", "Foggaret Ezzaouia", "In Ghar",
  ],
  "54": [
    "In Guezzam", "Tin Zaouatine",
  ],
  "55": [
    "Touggourt", "Nezla", "Tebesbest", "Zaouia El Abidia", "Megarine", "Sidi Slimane",
    "Blidet Amor", "El Allia", "Temacine", "Taibet",
  ],
  "56": [
    "Djanet", "Bordj El Haouas",
  ],
  "57": [
    "El Meniaa", "Hassi Gara", "Hassi Fehal",
  ],
  "58": [
    "El M'Ghair", "Djamaa", "Sidi Khelil", "Still", "Oum Touyour", "Tendla",
  ],
};
